"""Migrate Table

Revision ID: 1f63e75f2345
Revises: 5501264a0238
Create Date: 2022-08-02 12:16:41.147536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f63e75f2345'
down_revision = '5501264a0238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
