"""Migrate Table

Revision ID: 5501264a0238
Revises: f8ea1d93a993
Create Date: 2022-08-02 11:49:41.770530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5501264a0238'
down_revision = 'f8ea1d93a993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
