"""Migrate Table

Revision ID: 726988257ce1
Revises: 1f63e75f2345
Create Date: 2022-08-15 15:13:22.873031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '726988257ce1'
down_revision = '1f63e75f2345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waether',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waether_id'), 'waether', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waether_id'), table_name='waether')
    op.drop_table('waether')
    # ### end Alembic commands ###
