"""Migrate Table

Revision ID: f8ea1d93a993
Revises: 
Create Date: 2022-08-01 10:55:33.372601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8ea1d93a993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_rooms', 'address',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('class_rooms', 'slot2')
    op.alter_column('roll_calls', 'semester',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('roll_calls', 'year',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('student_subject_classes', 'semester',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('student_subject_classes', 'year',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('students', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='sextype'),
               nullable=True)
    op.alter_column('students', 'course',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('subjec_subject_classes', 'semester',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('subjec_subject_classes', 'year',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('teachers', 'level',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('teachers', 'specialize',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'specialize',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('teachers', 'level',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('subjec_subject_classes', 'year',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('subjec_subject_classes', 'semester',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('students', 'course',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('students', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='sextype'),
               nullable=False)
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('student_subject_classes', 'year',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('student_subject_classes', 'semester',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('roll_calls', 'year',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('roll_calls', 'semester',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('class_rooms', sa.Column('slot2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('class_rooms', 'address',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
