# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import unit_pb2 as unit__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/unit.Greeter/SayHello',
                request_serializer=unit__pb2.HelloRequest.SerializeToString,
                response_deserializer=unit__pb2.HelloReply.FromString,
                )
        self.SayHelloAgain = channel.unary_unary(
                '/unit.Greeter/SayHelloAgain',
                request_serializer=unit__pb2.HelloRequest.SerializeToString,
                response_deserializer=unit__pb2.HelloReply.FromString,
                )
        self.UnitById = channel.unary_unary(
                '/unit.Greeter/UnitById',
                request_serializer=unit__pb2.UnitByIdRequest.SerializeToString,
                response_deserializer=unit__pb2.UnitResponse.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloAgain(self, request, context):
        """Sends another greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnitById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=unit__pb2.HelloRequest.FromString,
                    response_serializer=unit__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHelloAgain,
                    request_deserializer=unit__pb2.HelloRequest.FromString,
                    response_serializer=unit__pb2.HelloReply.SerializeToString,
            ),
            'UnitById': grpc.unary_unary_rpc_method_handler(
                    servicer.UnitById,
                    request_deserializer=unit__pb2.UnitByIdRequest.FromString,
                    response_serializer=unit__pb2.UnitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unit.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unit.Greeter/SayHello',
            unit__pb2.HelloRequest.SerializeToString,
            unit__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unit.Greeter/SayHelloAgain',
            unit__pb2.HelloRequest.SerializeToString,
            unit__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnitById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unit.Greeter/UnitById',
            unit__pb2.UnitByIdRequest.SerializeToString,
            unit__pb2.UnitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
