# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nunit.proto\x12\x04unit\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0fUnitByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x04Unit\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04note\x18\x03 \x01(\t\"\xd9\x01\n\x0cUnitResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x15\n\rresponse_time\x18\x02 \x01(\t\x12\x13\n\x06status\x18\x03 \x01(\x08H\x00\x88\x01\x01\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x13\n\x06\x65rrors\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x1d\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32\n.unit.UnitH\x02\x88\x01\x01\x12\x11\n\x04logs\x18\x08 \x01(\tH\x03\x88\x01\x01\x42\t\n\x07_statusB\t\n\x07_errorsB\x07\n\x05_dataB\x07\n\x05_logs2\xad\x01\n\x07Greeter\x12\x32\n\x08SayHello\x12\x12.unit.HelloRequest\x1a\x10.unit.HelloReply\"\x00\x12\x37\n\rSayHelloAgain\x12\x12.unit.HelloRequest\x1a\x10.unit.HelloReply\"\x00\x12\x35\n\x08UnitById\x12\x15.unit.UnitByIdRequest\x1a\x12.unit.UnitResponseb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_UNITBYIDREQUEST = DESCRIPTOR.message_types_by_name['UnitByIdRequest']
_UNIT = DESCRIPTOR.message_types_by_name['Unit']
_UNITRESPONSE = DESCRIPTOR.message_types_by_name['UnitResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:unit.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:unit.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

UnitByIdRequest = _reflection.GeneratedProtocolMessageType('UnitByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNITBYIDREQUEST,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:unit.UnitByIdRequest)
  })
_sym_db.RegisterMessage(UnitByIdRequest)

Unit = _reflection.GeneratedProtocolMessageType('Unit', (_message.Message,), {
  'DESCRIPTOR' : _UNIT,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:unit.Unit)
  })
_sym_db.RegisterMessage(Unit)

UnitResponse = _reflection.GeneratedProtocolMessageType('UnitResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNITRESPONSE,
  '__module__' : 'unit_pb2'
  # @@protoc_insertion_point(class_scope:unit.UnitResponse)
  })
_sym_db.RegisterMessage(UnitResponse)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=20
  _HELLOREQUEST._serialized_end=48
  _HELLOREPLY._serialized_start=50
  _HELLOREPLY._serialized_end=79
  _UNITBYIDREQUEST._serialized_start=81
  _UNITBYIDREQUEST._serialized_end=110
  _UNIT._serialized_start=112
  _UNIT._serialized_end=162
  _UNITRESPONSE._serialized_start=165
  _UNITRESPONSE._serialized_end=382
  _GREETER._serialized_start=385
  _GREETER._serialized_end=558
# @@protoc_insertion_point(module_scope)
